services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'

  redis:
    image: "redis:latest"
    container_name: my_redis_cache
    ports:
      - "6379:6379"
    restart: unless-stopped