vaadin:
  launch-browser: true
spring:
  application:
    name: DBCPProject
  sql:
    init:
      mode: always
  #session:
    #store-type: redis
  cache:
    type: redis
    redis:
      time-to-live: 300000
      key-prefix: db_course_cache
      cache-null-values: false
  redis:
    port: 6379
    host: localhost